name: CI-Test-Self-Hosted

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Runner
        shell: powershell
        run: |
          echo "Runner is OK"

      - name: Test WSL
        shell: powershell
        run: |
          wsl -d Ubuntu -- echo "WSL is OK"
